--CREA LA TABLA DE PACIENTES
CREATE TABLE Pacientes(
id INT NOT NULL IDENTITY,
nombre VARCHAR(50) NOT NULL,
apellido VARCHAR(50) NOT NULL,
dni INT NOT NULL,
fecha_nacimiento DATE NOT NULL,
numero BIGINT NOT NULL, --NUMERO DE AFILIADO
atendido BIT NOT NULL,
obra_social VARCHAR(80) NOT NULL,
historia_clinica VARCHAR(MAX)
CONSTRAINT pk_id PRIMARY KEY (id)
)